DrinkVendingMachine/Controllers/AdminController.cs
using DrinkVendingMachine.DataService.Interface;
using DrinkVendingMachine.DTO;
using DrinkVendingMachine.Models;
using System.Web.Mvc;
using System.Web;
using System.IO;

namespace DrinkVendingMachine.Controllers
{
    [Authorize]
    public class AdminController : BaseController
    {
        private readonly IAdminService adminService;

        public AdminController(IAdminService adminService)
        {
            this.adminService = adminService;
        }

        private AdminModel getAdminModel()
        {
            return new AdminModel(
                adminService.GetDrinks(),
                adminService.GetCoins()
                );
        }
        public ActionResult Index()
        {
            return View(getAdminModel());
        }
        
        public ActionResult Drink(long id)
        {
            DrinkDTO dto = adminService.GetDrink(id);
            DrinkModel model = new DrinkModel()
            {
                Id = dto.Id,
                Cost = dto.Cost,
                Count = dto.Count,
                Ord = dto.Ord
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Drink(DrinkModel model, HttpPostedFileBase fileUpload)
        {
            DrinkDTO dto = new DrinkDTO()
            {
                Id = model.Id,
                Cost = model.Cost,
                Count = model.Count,
                Ord = model.Ord,
            };
            byte[] image = null;
            if (fileUpload != null)
            {
                using (var binaryReader = new BinaryReader(fileUpload.InputStream))
                {
                    image = binaryReader.ReadBytes(fileUpload.ContentLength);
                }
            }

            if (execute(delegate ()
             {
                 adminService.SaveDrink(dto, image);
             }))
            {
                return View("Index", getAdminModel());
            }
            else
            {
                return View(model);
            };

            
        }

        public ActionResult DeleteDrink(long id)
        {
            adminService.DeleteDrink(id);
            return View("Index", getAdminModel());
        }
        public ActionResult Coin(long id)
        {
            CoinDTO dto = adminService.GetCoin(id);
            CoinModel model = new CoinModel
            {
                 Id = dto.Id,
                 Count = dto.Count,
                 Denomination = dto.Denomination,
                 Lock = dto.Lock
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Coin(CoinModel model)
        {
            CoinDTO dto = new CoinDTO
            {
                Id = model.Id,
                Count = model.Count,
                Lock = model.Lock,
                Denomination = model.Denomination
            };
                        
            if (execute(delegate ()
             {
                 adminService.UpdateCoin(dto);
             }))
            {
                return View("Index", getAdminModel());
            }
            else
            {
                return View(model);
            };

            
        }
        
    }
}

DrinkVendingMachine/Controllers/ImageController.cs
using DrinkVendingMachine.DataService.Interface;
using System.Web.Mvc;

namespace DrinkVendingMachine.Controllers
{
    public class ImageController : Controller
    {
        private readonly IImageService imageService;

        public ImageController(IImageService imageService)
        {
            this.imageService = imageService;
        }

        public ActionResult GetImageFile(long drinkId)
        {
            var imageBody = imageService.GetImageBody(drinkId);
            return new FileStreamResult(new System.IO.MemoryStream(imageBody), "image/jpeg");
        }
    }
}

DrinkVendingMachine/Views/Admin/Coin.cshtml
@using DrinkVendingMachine.Models
@using DrinkVendingMachine.Resources
@model CoinModel


<div class="row">
    <h1>Монета @if (Model.Id == 0) { <text>[новый]</text> } else {<text>[редактирование]</text>}</h1>
    
    <div class="col-md-8">
        
        @using (@Html.BeginForm("Coin", "Admin", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            
            

            <div class="form-group">
                @Html.LabelFor(m => m.Count)
                @Html.TextBoxFor(m => m.Count, new { @class = "form-control", required = true, @type = "number" })
                @Html.ValidationMessageFor(m => m.Count)
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Lock)
                @Html.CheckBoxFor(m => m.Lock)
            </div>
            

            <div class="row">
                <div class="col-md-6">
                    
                </div>
                <div class="col-md-6">
                    <button class="btn btn-primary" type="submit">@Resource.Action_Save</button>
                    <a class="btn btn-default" href="@Url.Action("Index", "Admin")">@Resource.Action_Cancel</a>
                </div>
            </div>

        }

    </div>
</div>

DrinkVendingMachine/Views/Admin/Drink.cshtml
@using DrinkVendingMachine.Models
@using DrinkVendingMachine.Resources
@model DrinkModel


<div class="row">
    <h1>Напиток @if (Model.Id == 0) { <text>[новый]</text> } else {<text>[редактирование]</text>}</h1>
    
    <div class="col-md-8">
        
        @using (@Html.BeginForm("Drink", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.ValidationMessage("ErrorGeneralMessage")
            @Html.AntiForgeryToken()
            
            <div class="form-group">
                @Html.LabelFor(m => m.Cost)
                @Html.TextBoxFor(m => m.Cost, new { @class = "form-control", required = true, autofocus = true })
                @Html.ValidationMessageFor(m => m.Cost)
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Count)
                @Html.TextBoxFor(m => m.Count, new { @class = "form-control", required = true, @type = "number" })
                @Html.ValidationMessageFor(m => m.Count)
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Ord)
                @Html.TextBoxFor(m => m.Ord, new { @class = "form-control", required = true, @type = "number" })
            </div>

            if (Model.Id > 0)
            {
                <div class="form-group">
                    <img style="width: 300px; max-width:300px" src="@Url.Action( "GetImageFile", "Image", new { drinkId = Model.Id } )">
                </div>
            }



            <div class="form-group">
                <label>@if (Model.Id == 0) { <text>Файл изображения</text> } else {<text>Новый файл изображения</text>}</label>
                <input type="file" name="fileUpload" />
            </div>


            <div class="row">
                <div class="col-md-6">
                   
                </div>
                <div class="col-md-6">
                    <button class="btn btn-primary" type="submit">@Resource.Action_Save</button>
                    
                    @if (Model.Id > 0)
                    {
                        <a class="btn btn-default" href="@Url.Action("DeleteDrink", "Admin",new { id = Model.Id })">@Resource.Action_Delete</a>
                    } 

                    <a class="btn btn-default" href="@Url.Action("Index", "Admin")">@Resource.Action_Cancel</a>
                </div>
            </div>

        }

    </div>
</div>

DrinkVendingMachine/Views/Admin/Index.cshtml
@using DrinkVendingMachine.Models
@model AdminModel


<div class="row">
    <h1>Монеты для сдачи</h1>
    
    @foreach (var coin in Model.Coins)
    {
        <div class="col-md-3">
            
            <h1>@coin.Denomination</h1>
            <div>Кол-во: @coin.Count</div>
            @if (coin.Lock)
            {
                <div>Заблокирован приём</div>
            }
            <div>@Html.ActionLink("Редактировать", "Coin", "Admin", new { id = coin.Id }, null)</div>
            
        </div>
    }
</div>

<div class="row">
    <h1>Напитки</h1>
            
    <div>@Html.ActionLink("Добавить новый напиток", "Drink", "Admin", new { id = 0 }, null)</div>
        
    @foreach (var drink in Model.Drinks)
    {
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img style="width: 300px; max-width:300px" src="@Url.Action( "GetImageFile", "Image", new { drinkId = drink.Id } )">
                <div class="caption">
                    <h3><span style="margin: 10px">Цена: @drink.Cost</span> <span style="margin: 10px">Кол-во: @drink.Count</span></h3>
                    <p>
                        <span>Сортировка: @drink.Ord</span>
                    </p>
                    <p>
                        @Html.ActionLink("Редактировать", "Drink", "Admin", new { id = drink.Id }, null)
                        @Html.ActionLink("Удалить", "DeleteDrink", "Admin", new { id = drink.Id }, null)
                    </p>
                </div>
            </div>
        </div>
    }
    
</div>