DrinkVendingMachine/Controllers/ImageController.cs
using DrinkVendingMachine.DataService.Interface;
using System.Web.Mvc;

namespace DrinkVendingMachine.Controllers
{
    public class ImageController : Controller
    {
        private readonly IImageService imageService;

        public ImageController(IImageService imageService)
        {
            this.imageService = imageService;
        }

        public ActionResult GetImageFile(long drinkId)
        {
            var imageBody = imageService.GetImageBody(drinkId);
            return new FileStreamResult(new System.IO.MemoryStream(imageBody), "image/jpeg");
        }
    }
}

DrinkVendingMachine/Controllers/ShoppingСartController.cs
using DrinkVendingMachine.DataService.Interface;
using DrinkVendingMachine.DTO;
using DrinkVendingMachine.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace DrinkVendingMachine.Controllers
{
    public class ShoppingСartController : BaseController
    {
        private readonly IShoppingСartService shoppingСartService;
        public ShoppingСartController(IShoppingСartService shoppingСartService)
        {
            this.shoppingСartService = shoppingСartService;
        }

        private ShoppingСartModel getShoppingСartModel()
        {
            IList<SurrenderCoinDTO> surrender = new List<SurrenderCoinDTO>();
            bool canbeSurrender = shoppingСartService.GetSurrender(ref surrender);

            return new ShoppingСartModel(
                shoppingСartService.GetDrinks(),
                shoppingСartService.GetCoins(),
                surrender,
                canbeSurrender,
                shoppingСartService.GetShoppingСartTotalPayment(),
                shoppingСartService.GetShoppingСartTotalCost()
                );

        }

        public ActionResult Index()
        {
            shoppingСartService.Init();
            return View(getShoppingСartModel());
        }
                
        public ActionResult SelectDrink(long id)
        {
            shoppingСartService.SelectDrink(id);
            return View("Index", getShoppingСartModel());
        }
                
        public ActionResult Pay(long id)
        {
            shoppingСartService.Pay(id);
            return View("Index", getShoppingСartModel());
        }

        [HttpPost]
        public ActionResult Purchase()
        {
            shoppingСartService.Purchase();
            shoppingСartService.Init();
            return View("Index", getShoppingСartModel());
        }
        
    }
}

DrinkVendingMachine/Views/ShoppingСart/Index.cshtml
@using DrinkVendingMachine.Models
@using DrinkVendingMachine.Resources
@model ShoppingСartModel

<div class="row">
    <h1>Оплата:</h1>

    @foreach (var coin in Model.Coins)
    {
        <div class="col-md-3" style="text-align: center">

            <h1>@coin.Denomination</h1>
            
            @if (!coin.Lock)
            {
                <div>@Html.ActionLink("Оплатить", "Pay", "ShoppingСart", new { id = coin.Id }, null)</div>
            }
            else
            {
                <div>@Resource.Label_Lock</div>
            }

        </div>
    }
</div>
<div class="row">
    <div class="col-md-4"><h1>Оплачено: @((decimal)Model.ShoppingСartTotalPayment / 100)</h1></div>
    <div class="col-md-4"><h1>Стоимость: @Model.ShoppingСartTotalCost</h1></div>
    <div class="col-md-4">
        @if (Model.CanbeSurrender)
        {
            <h1>Сдача (монеты):</h1>
            foreach (var s in Model.Surrender)
            {
                <div><h2>@s.Denomination (@s.Count)</h2></div>
            }
        }
        else
        {
            <h1 style="color:red">Автомат не может выдать сдачу</h1>
        }

    </div>
</div>

<div class="row">
    <h1>Напитки:</h1>

    @foreach (var drink in Model.Drinks)
    {

        <div class="col-sm-6 col-md-4">
            <div class="thumbnail" style="background-color: @if (drink.Selected) { <text>greenyellow</text> }">
                <img style="width: 300px; max-width:300px" src="@Url.Action( "GetImageFile", "Image", new { drinkId = drink.Id } )">
                <div class="caption">
                    <h3>Цена: @drink.Cost, Кол-во: @drink.Count</h3>
                    <p>
                        @if (Model.ShoppingСartTotalPayment > 0)
                        {
                            if (drink.CanbeSelected)
                            {
                                @Html.ActionLink("Выбрать", "SelectDrink", "ShoppingСart", new { id = drink.Id }, null)
                            }
                            else if(drink.Selected)
                            {
                                @Html.ActionLink("Отменить", "SelectDrink", "ShoppingСart", new { id = drink.Id }, null)
                            }
                        }
                        

                    </p>
                </div>
            </div>
        </div>
    }
</div>


<div class="row">

    <div class="col-md-8">

        @using (@Html.BeginForm("Purchase", "ShoppingСart", FormMethod.Post))
        {
            if (Model.ShoppingСartTotalPayment > 0 && Model.ShoppingСartTotalCost > 0 && Model.CanbeSurrender)
            {
                <button class="btn btn-primary" type="submit">@Resource.Action_Purchase</button>
            }
        }
    </div>
</div>